# Generated by Django 5.1.1 on 2024-10-09 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Citi_village',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
        migrations.DeleteModel(
            name='Training_for_beginners',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Сountry',
        ),
        migrations.RemoveConstraint(
            model_name='profile',
            name='unique_location',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='connection_2_country',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='connection_1_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='connection_3_region',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='connection_4_district',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='connection_5_citi_village',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='connection_6_street',
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='main.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_villages', to='main.district'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.cityvillage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='main.country'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('country', 'region', 'district', 'city_village'), name='unique_location'),
        ),
    ]
