# Generated by Django 5.1.1 on 2024-11-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='unique_location',
        ),
    ]
