# Generated by Django 5.1.1 on 2024-10-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cityvillage_country_delete_citi_village_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='comment',
        ),
        migrations.AlterField(
            model_name='plane',
            name='date_publications',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plane',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plane',
            name='photo',
            field=models.ImageField(upload_to='planes/'),
        ),
    ]
