# Generated by Django 5.1.1 on 2024-10-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_plane_comment_alter_plane_date_publications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='plan',
            field=models.ImageField(default=1, upload_to='plan/'),
            preserve_default=False,
        ),
    ]
