# Generated by Django 5.1.1 on 2024-10-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_plane_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='bal',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plane',
            name='comment',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
