# Generated by Django 5.1.1 on 2024-10-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_plane_bal_plane_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
